[package]
name = "orbit_types"
version = "0.1.0"
edition = "2021"

[dependencies]
orbit_derive = { version = "0.1.0", path = "../orbit_derive" }
postgres-types = { version = "0.2.6", features = ["derive"] }
serde = "1.0.195"
serde_json = "1.0.111"
tokio-postgres = { version = "0.7.10" }
