[package]
name = "orbit_types"
version = "0.1.0"
edition = "2021"

[dependencies]
orbit_derive.workspace = true

postgres-types.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-postgres.workspace = true
